### PR TITLE
Added some utilities to facilitate easier logging within plugins.  Thank...

### PR DESCRIPTION
**Pull request by timclemons**
...s to

binding, it's no longer necessary to pass around the log as a function
parameter.

### CODE REVIEW

**Comment by hugoduncan** [comment]
Hi, looks like a good idea :)

I'm not too clear why MockLogger is necessary - are there specific cases where the logger is not set?

**Comment by timclemons** [comment]
MockLogger is useful for calling individual plugin functions from a REPL where they might very well be getting called outside the context of with-log.  Conceivably, it could also be extended to store and verify log requests during unit tests.

**Comment by hugoduncan** [comment]
So MockLogger is for development and test? Just wondering if it should go on the test classpath, rather than in the main source...

**Comment by timclemons** [comment]
It could certainly be moved over to test without affecting logging in the plugins.  However, we then have a situation where all the logging functions (and functions that call them) throw a NullPointerException when not wrapped in with-log.  I thought it safer that logging be a no-op rather than a runtime failure in situations where code is called out of its normal context.

That said, I can see where developers might prefer fast failure in these instances.

**Comment by hugoduncan** [comment]
I think fail fast is preferable to having logging output silently discarded.

I believe the calls to check whether a level is enabled are superfluous as written. If debug/warn/info were macros, I could understand why we would want to prevent argument evaluation (they should probably be macros, and use `when` rather than `if`).

Comparing the logging functions to tools.logging, I think the argument order should be changed to match. ie `(debug [e msg])`.

Finally it might also be nice to add `debugf` and friends, taking a format string and arguments.

**Comment by timclemons** [comment]
Sounds reasonable.  I'll see when I can work on the implementation.

**Comment by timclemons** [comment]
Work has been implemented.  Although I did remove MockLogger, I'm still ensuring that the logging doesn't fail when _plexus-log_ is nil.  When I left the nil? check out it resulted in build errors during the phase where mojo metadata was getting extracted from the Maven plugins.

**Comment by hugoduncan** [comment]
Excellent stuff! I've pulled this into zi 0.5.0-SNAPSHOT as a single commit. Many thanks - it makes logging much less arduous.

**Pull request closed without merging**
