### PR TITLE
Refined log.clj

### PR DESCRIPTION
**Pull request by timclemons**
- Added ^{:dynamic true} to _plexus-log_ definition.  This should keep the binding working once the project is merged to Clojure 1.3.
- Abstracted a lot of the duplicate code with the (deflog) macro.

### CODE REVIEW

**Comment by timclemons** [comment]
Just noticed that you've already updated the code for Clojure 1.3.  However, the deflog macro might be of use.

**Comment by hugoduncan** [comment]
The deflog macro is definitely useful - thanks for putting this together.

I think it would be nicer if it used non-gensymed symbols for the generated argument lists though, so that editors that display the arglist don't show things like ([mesg__3421__auto__] [e__3422__auto__ mesg__3421__auto__]).

**Comment by timclemons** [comment]
Ok, I've replaced the gensyms with unqualified symbols.

**Comment by hugoduncan** [comment]
Applied as 3ef1a56065afce5e6550504aedc231ecdf8b54da

It might be helpful to us both if you put pull requests on a branch, so that they can be rebased against upstream/develop with `git rebase -p upstream/develop`, which avoids merge commits in the pull request.

I really appreciate the improvements you're making :) Shout if you need a release with these changes in, otherwise I'll probably cut another release in a week or two (I am sort of waiting on a 1.3 compatible marginalia release).  As you probably noticed, I updated to the latest aether dependency, but haven't had time to try out the support for list parameters (such as for the namespace list in the test mojo).

**Pull request closed without merging**
